add domain to customer
nuts-foundation/nuts-registry-admin-demo pull request #46
Opened 2021-06-02 14:20 UTC by woutslakhorst

also simplified some of the customer request objects.

2021-06-11 11:34 UTC, reinkrul requested changes

2021-06-11 11:34 UTC, reinkrul commented on web/src/admin/CustomerForm.vue
> +      <label for="customerCityInput">Domain:</label>
label ref is incorrect

2021-06-14 08:07 UTC, stevenvegt commented
Can we put this on on hold and wait after #45 ? In there I refactored the customer already. I offer to fix the merge conflicts.

2021-06-17 11:08 UTC, reinkrul approved these changes

2021-06-17 11:08 UTC, merged